BEGIN;
DROP TABLE IF EXISTS export_downloads;
DROP TABLE IF EXISTS backup_checkpoints;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS search_items;
DROP TABLE IF EXISTS journal_projections;
DROP TABLE IF EXISTS mutation_requests;
DROP TABLE IF EXISTS collection_shares;
DROP TABLE IF EXISTS family_invitations;
DROP TABLE IF EXISTS oauth_tokens;
DROP TABLE IF EXISTS oauth_grants;
DROP TABLE IF EXISTS oauth_clients;
DROP TABLE IF EXISTS auth_challenges;
DROP TABLE IF EXISTS web_sessions;
DROP TABLE IF EXISTS user_preferences;
DROP TABLE IF EXISTS memberships;
DROP TABLE IF EXISTS households;
DROP TABLE IF EXISTS external_identities;
DROP TABLE IF EXISTS users;
COMMIT;
